plugin "cocoapods-mPaaS"
source "https://code.aliyun.com/mpaas-public/podspecs.git"

mPaaS_baseline '10.1.68'  # 请将 x.x.x 替换成真实基线版本
mPaaS_version_code 25   # This line is maintained by MPaaS plugin automatically. Please don't modify.

platform :ios, "8.0"

target "MPShareDemo_pod" do    
    
    mPaaS_pod "mPaaS_Share"
    mPaaS_pod "mPaaS_CommonUI"
    
end
